#ifndef __FRAMEWORK_GLOBAL_H__
#define __FRAMEWORK_GLOBAL_H__

#include <commondefs.h>

#if defined(FRAMEWORK_LIBRARY)
#  define FRAMEWORK_EXPORT DECL_EXPORT
#elif defined(FRAMEWORK_STATIC_LIBRARY)
#  define FRAMEWORK_EXPORT
#else
#  define FRAMEWORK_EXPORT DECL_IMPORT
#endif

#if defined(GLOBAL_NAMESPACE)
#  define FRAMEWORK_BEGIN_NAMESPACE BEGIN_NAMESPACE(GLOBAL_NAMESPACE)
#  define FRAMEWORK_END_NAMESPACE END_NAMESPACE(GLOBAL_NAMESPACE)
#else
#define GLOBAL_NAMESPACE framework
#endif
#define FRAMEWORK_BEGIN_NAMESPACE BEGIN_NAMESPACE(GLOBAL_NAMESPACE)
#define FRAMEWORK_END_NAMESPACE END_NAMESPACE(GLOBAL_NAMESPACE)
#define FRAMEWORK_NAMESPACE GLOBAL_NAMESPACE



#endif