#ifndef __FRAMEWORK_GLOBAL_H__
#define __FRAMEWORK_GLOBAL_H__

#include <memory>
#include <core.h>

#ifdef framework_EXPORTS
#  define FRAMEWORK_EXPORT DECL_EXPORT
#else
#  define FRAMEWORK_EXPORT DECL_IMPORT
#endif

#define FRAMEWORK_VERSION_STRING "0.1.0"
#define FRAMEWORK_VERSION_MAJOR 0
#define FRAMEWORK_VERSION_MINOR 1
#define FRAMEWORK_VERSION_PATCH 0
#define FRAMEWORK_VERSION_QUALIFIER
#define FRAMEWORK_VERSION_HEXA ((FRAMEWORK_VERSION_MAJOR << 24) | (FRAMEWORK_VERSION_MINOR << 16) | (FRAMEWORK_VERSION_PATCH << 8))

#ifndef FRAMEWORK_GLOBAL_NAMESPACE
#  define FRAMEWORK_GLOBAL_NAMESPACE framework
#endif

#define FRAMEWORK_BEGIN_NAMESPACE BEGIN_NAMESPACE(FRAMEWORK_GLOBAL_NAMESPACE)
#define FRAMEWORK_END_NAMESPACE END_NAMESPACE(FRAMEWORK_GLOBAL_NAMESPACE)
#define FRAMEWORK_NAMESPACE FRAMEWORK_GLOBAL_NAMESPACE


#endif
