

function(disable_warnings)
    if(WIN32)
        target_compile_options(${PROJECT_NAME} PRIVATE /FI${CMAKE_SOURCE_DIR}/cmake/disable_warnings.h)
    else()
        target_compile_options(${PROJECT_NAME} PRIVATE -include ${CMAKE_SOURCE_DIR}/cmake/disable_warnings.h)
    endif()
endfunction()

function(find_target_or_filter _target)
    cmake_parse_arguments(ARGS "" "" "FOLDERS;FILTERS" ${ARGN})
    set(result "")
    foreach(folder ${ARGS_FOLDERS})
        if(EXISTS ${folder})
            foreach(filter ${ARGS_FILTERS})
                file(GLOB_RECURSE files "${folder}/${filter}")
                list(APPEND result ${files})
            endforeach()
        else()
            message(WARNING "Folder ${folder} does not exist.")
        endif()
    endforeach()
    set(${_target} "${result}" PARENT_SCOPE)
endfunction()


function(set_files_filter_group _target)
    foreach(_file IN LISTS ARGV)
        get_filename_component(_dir "${_file}" PATH)
        string(REPLACE "${CMAKE_CURRENT_SOURCE_DIR}/" "" _group_path "${_dir}")
        string(REPLACE "/" "\\" _group_path "${_group_path}")
        source_group("${_group_path}" FILES "${_file}")
    endforeach()
endfunction()