#ifndef __COMMON_GLOBAL_H__
#define __COMMON_GLOBAL_H__

#include <commondefs.h>

#include <memory>

#if defined(COMMON_LIBRARY)
#  define COMMON_EXPORT DECL_EXPORT
#elif defined(COMMON_STATIC_LIBRARY)
#  define COMMON_EXPORT
#else
#  define COMMON_EXPORT DECL_IMPORT
#endif

#if defined(GLOBAL_NAMESPACE)
#  define COMMON_BEGIN_NAMESPACE BEGIN_NAMESPACE(GLOBAL_NAMESPACE)
#  define COMMON_END_NAMESPACE END_NAMESPACE(GLOBAL_NAMESPACE)
#else
#define GLOBAL_NAMESPACE common
#endif
#define COMMON_BEGIN_NAMESPACE BEGIN_NAMESPACE(GLOBAL_NAMESPACE)
#define COMMON_END_NAMESPACE END_NAMESPACE(GLOBAL_NAMESPACE)
#define COMMON_NAMESPACE GLOBAL_NAMESPACE



#endif